# Generated by Django 2.2.17 on 2021-01-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attach',
            field=models.FileField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
