# Generated by Django 2.2.17 on 2021-01-31 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_user', '0002_auto_20210131_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_send_to_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_send_mentor', to='mentor_user.UserProfile'),
        ),
    ]
