# Generated by Django 2.2.17 on 2021-01-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_user', '0003_message_msg_send_to_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replays',
        ),
        migrations.AddField(
            model_name='replay',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor_user.Message'),
        ),
    ]
